### PR TITLE
Made the gimbal xacro topics match the camera plugin

### PR DESCRIPTION
**Pull request by skyler237**
This helps to make applications using image transport easier

### CODE REVIEW

**Review by jerelbn — CHANGES_REQUESTED** [review]
Can we change `image_camera_info_topic` to `camera_info_topic`? It should also be changed in camera.xacro

**Review by plusk01 — APPROVED** [review]
There is that gross <kbd>tab</kbd> before `frame_rate` you could remove if you felt so inclined. :smile: 

Also, I agree with @jerelbn.

**Comment by gellings** [comment]
I could be wrong but I thought that the old way was appropriate for using image transport.  Maybe I need to be educated at why this is better.

**Comment by skyler237** [comment]
I also am not too familiar with image transport, so correct me if I am wrong, but I had problems passing the gimbal plugin data to the visual_frontend node (using image transport) because the gimbal was publishing on the topics /camera/image_raw and /camera/image_raw/camera_info, but image transport seemed to expect the image_raw and camera_info topics to both be under the same namespace (i.e. /camera/image_raw and /camera/camera_info.

**Review by jerelbn — APPROVED** [review]

**Comment by jerelbn** [comment]
I'm not sure what the difference between the old and new ways of using image_transport are but having the option to change topic names in plugins is useful I think.

**Comment by skyler237** [comment]
I also just changed image_camera_info_topic to camera_info_topic and removed the weird tab

**Review by gellings — APPROVED** [review]
Sounds good

**Pull request merged**
